import type { CustomizationLevel, CustomizationLevelInfo } from '@/types/product';

export const CUSTOMIZATION_LEVELS: Record<CustomizationLevel, CustomizationLevelInfo> = {
  1: {
    level: 1,
    name: 'Surface Customization',
    emoji: '\u{1F7E2}',
    coreDefinition: 'Visual changes only',
    typicalForms: ['Logo printing', 'Engraving', 'Packaging print', 'Minor color change'],
    keyRisk: 'MOQ not surfaced early',
    setupFee: 'Yes (low)',
    moqImpact: 'Negotiable',
    costBehavior: 'Linear, predictable',
    reworkCost: 'Low',
    timelineRisk: 'Low',
    supplierAvailability: 'Many',
    feasibility: 'Very High',
    developmentTime: '1-7 days',
    bestFor: 'First orders, low budget, fast turnaround',
    earlyWarningSignal: 'Check MOQ before quoting',
  },
  2: {
    level: 2,
    name: 'Component-Level',
    emoji: '\u{1F7E1}',
    coreDefinition: 'Component modified, structure intact',
    typicalForms: ['Custom box design', 'Label insert', 'Motor spec', 'Inner material'],
    keyRisk: 'Rework cost + component supplier mismatch',
    setupFee: 'Yes (moderate)',
    moqImpact: 'May shift per component',
    costBehavior: 'Moderate jump',
    reworkCost: 'Moderate',
    timelineRisk: 'Moderate',
    supplierAvailability: 'Moderate',
    feasibility: 'High',
    developmentTime: '7-15 days',
    bestFor: 'Mid-size orders with specific component needs',
    earlyWarningSignal: 'Confirm component specs before production starts',
  },
  3: {
    level: 3,
    name: 'Structural (No Mold)',
    emoji: '\u{1F7E0}',
    coreDefinition: 'Structure changed, no new mold',
    typicalForms: ['Size modification', 'Capacity change', 'Material composition', 'Structural adjustment'],
    keyRisk: 'Wrong structural parameter locked in early',
    setupFee: 'Yes (moderate-high)',
    moqImpact: 'Constrained by tooling limits',
    costBehavior: 'Significant jump',
    reworkCost: 'High',
    timelineRisk: 'High',
    supplierAvailability: 'Limited',
    feasibility: 'Moderate',
    developmentTime: '15-30 days',
    bestFor: 'Established clients needing structural fit',
    earlyWarningSignal: 'Confirm ALL dimensions before sampling',
  },
  4: {
    level: 4,
    name: 'Mold/Engineering',
    emoji: '\u{1F534}',
    coreDefinition: 'New tooling/mold required',
    typicalForms: ['Custom outsole', 'Vending machine', 'Kids cosmetic mold', 'Specialized equipment'],
    keyRisk: 'MOQ far exceeds client needs',
    setupFee: 'Yes (very high mold fee)',
    moqImpact: 'Very high, rarely negotiable',
    costBehavior: 'High, non-linear',
    reworkCost: 'Very High',
    timelineRisk: 'Very High',
    supplierAvailability: 'Few',
    feasibility: 'Low-Moderate',
    developmentTime: '30-90 days',
    bestFor: 'High-volume, funded projects with clear specs',
    earlyWarningSignal: 'Confirm client volume vs mold MOQ upfront',
  },
  5: {
    level: 5,
    name: 'Multi-Component System',
    emoji: '\u26AB',
    coreDefinition: 'Multiple components + processes + suppliers',
    typicalForms: ['Jewelry set', 'Multi-SKU', 'Textile + metal + print assembly'],
    keyRisk: 'System economics fail even when individual parts are feasible',
    setupFee: 'Yes (multiple setup fees)',
    moqImpact: 'Stacks across all components',
    costBehavior: 'Non-linear, compounding',
    reworkCost: 'Extreme',
    timelineRisk: 'Extreme',
    supplierAvailability: 'Very Few (multiple needed)',
    feasibility: 'Low',
    developmentTime: '60-120+ days',
    bestFor: 'Large scale, premium products, well-resourced buyers',
    earlyWarningSignal: 'Map ALL components + MOQs before committing',
  },
};

export const CATEGORY_SAMPLES: Record<string, {
  name: string;
  percentage: string;
  customizationTypes: { type: string; percentage: string; examples: string; complexity: string }[];
  keyDetails: string[];
}> = {
  'bags-leather': {
    name: 'Bags & Leather Goods',
    percentage: '35%',
    customizationTypes: [
      { type: 'Logo Addition (D-rings/hardware)', percentage: '40%', examples: 'D-ring shoulder strap attachment', complexity: 'Medium' },
      { type: 'Logo Embossing/Printing', percentage: '30%', examples: 'Leather stamp, heat press logo', complexity: 'Medium-High' },
      { type: 'Label Replacement', percentage: '20%', examples: 'Replacing tag with custom logo', complexity: 'Low-Medium' },
      { type: 'No Customization', percentage: '10%', examples: 'Stock items with supplier logo', complexity: 'None' },
    ],
    keyDetails: [
      'Purple bag case: Added D-ring hardware (\u00A52 extra per unit) + logo embossing',
      'Computer bags: White bottom/black text fabric label replacement',
      'Logo rubber tags require minimum 1,000 units (cannot do for 100-unit order)',
    ],
  },
  'packaging-paper': {
    name: 'Packaging Materials (Paper Bags)',
    percentage: '30%',
    customizationTypes: [
      { type: 'Full Color Printing', percentage: '60%', examples: 'CMYK logo on white kraft', complexity: 'Medium' },
      { type: 'Single Color Print', percentage: '30%', examples: 'One color logo', complexity: 'Low' },
      { type: 'Stock/No Print', percentage: '10%', examples: 'Plain bags', complexity: 'None' },
    ],
    keyDetails: [
      'Color printing MOQ: 1,000 units (some suppliers); 500 units (premium pricing)',
      'Size: 21\u00D714\u00D727cm with white round rope handles',
      'Lead time: 12-15 days for custom printing',
      'Full color pricing: +400% vs stock (\u00A50.58 \u2192 \u00A53.00)',
    ],
  },
};
